image: Visual Studio 2017

platform:
  - x64

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - ps: cd Tools
  - npm install
  - ps: cd ..\ElectronClient\app
  - npm install
  - yarn dist
  - cd .\dist\
  - rmdir /s/q .\win-unpacked\locales
  - rename win-unpacked YAN-Windows-portable-x86_64
  - ps: cd ..\..\..\

after_build:
  - 7z a YAN-Windows-portable-x86_64.zip .\ElectronClient\app\dist\YAN-Windows-portable-x86_64\
  
test: off

artifacts:
- path: YAN-Windows-portable-x86_64.zip
