image: Visual Studio 2017

platform:
  - x64

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - ps: cd Tools
  - npm install
  - ps: cd ..\ElectronClient\app
  - npm install
  - yarn dist
  - rmdir /s/q .\dist\win-unpacked\locales
  - ps: cd ..\..\

after_build:
  - 7z a YAN-x86_64-Windows-portable.zip .\ElectronClient\app\dist\win-unpacked\
  
test: off

artifacts:
- path: YAN-x86_64-Windows-portable.zip
