image: Visual Studio 2017

platform:
  - x64

# cache:
  # Not caching node_modules because appveyor doesn't restore it afterwards (not sure why)
  # - node_modules
  # - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - ps: cd Tools
  - npm install
  - ps: cd ..\ElectronClient\app
  - ps: xcopy /C /I /H /R /Y /S ..\..\ReactNativeClient\lib lib
  - npm install
  - yarn dist
  - ps: cd ..\..\

after_build:
  - 7z a ElectronClient.Src.7z .\ElectronClient\app
  
test: off

artifacts:
- path: ElectronClient.Src.7z
